### ISSUE TITLE
Namespace in violation with Cleverbot.io's wrapper

### ISSUE THREAD

**Issue by velddev** [velddev/Cleverbot.Net#10]
the project id of the package is named `Cleverbot`, however the namespaces used are `Cleverbot.Net`, this kind of conflicts with [Cleverbot.Net](https://github.com/Sorashi/Cleverbot.Net).

Should we go to just Cleverbot?

**Comment by DynamicField** [comment]
Normally the package id doesn't conflict with the namespace :/.
