### ISSUE TITLE
Fix Nuget

### ISSUE THREAD

**Issue by hadad95** [velddev/Cleverbot.Net#2]
There's a really terrible mistake you made in nuget. check it out real quick and fix it.

**Comment by velddev** [comment]
Oh, I'll check it out ASAP. I don't have much experience with nuget.

**Comment by ViolentCrumble** [comment]
yeah can't seem to create a cleverbot due to a naming issue?

**Comment by DynamicField** [comment]
You'd need to replace the ID with something different than the title.

**Comment by hadad95** [comment]
no. it's a security issue. I really don't know how to explain more without making it obvious, and there's no way to contact the developer directly. so here's a hint: bat

**Comment by velddev** [comment]
🤔 Security issue? That doesn't seem right

EDIT: I see, It has issues calling Cleverbot because the namespace is also called cleverbot

**Comment by aosama95** [comment]
I can see your nuget API key man lol. check out the package now

**Comment by velddev** [comment]
Oh, I didn't realize this, I'll delete your comment and fix it

**Comment by captainswain** [comment]
Any luck with this?

**Comment by velddev** [comment]
I've updated the package, but the naming issue still consists.

**Comment by velddev** [comment]
For now, you can fix it by calling Cleverbot by doing Cleverbot.Net.Cleverbot, but i'll update it to CleverbotSession in a few minutes

**Comment by velddev** [comment]
I've updated the package, please update to 0.8.1

**Comment by hadad95** [comment]
can you remove the previous versions from nuget though? it wouldn't have achieved you anything if it's still there

**Comment by velddev** [comment]
I've deleted this key, and it no longer works.

But I'll delete it, thanks for mentioning

**Comment by hadad95** [comment]
my pleasure. this issue is no longer needed
