### ISSUE TITLE
CleverbotResponse.Response returning null?

### ISSUE THREAD

**Issue by oxkitsune** [velddev/Cleverbot.Net#4]
So I'm using this:
`                CleverbotResponse r = session.GetResponseAsync(msg).Result;
                e.Channel.SendMessage(r.Response);`
But it's returning null when I use r.Response? I've setup everything correctly.

**Comment by FreezyLemon** [comment]
Same here. I implement it a bit differently but I have the same problem:
Using both GetResponse and GetResponseAsync, I get a Response object with everything set to a (correct?) value except for ConversationId and Response, which are both null.

**Comment by velddev** [comment]
I think i know why, I'll push a update within an hour.

**Comment by velddev** [comment]
This has been fixed and uploaded to nuget, please confirm if it works for your application.

**Comment by oxkitsune** [comment]
It works now, however I had to manually download the files because I couldnt get them through nuget. Not sure if this happens only for me. Anyways thanks a lot!
