### ISSUE TITLE
Updte to work with dotnet core/netstandard 1.3

### ISSUE THREAD

**Issue by Cisien** [velddev/Cleverbot.Net#5]
Other than targeting the new project system, the only code changes needed are to switch from WebClient to HttpClient, and to use GetTypeInfo() when looking up fields.

see https://github.com/Cisien/OniBot/commit/fee007424f

**Comment by velddev** [comment]
I'll look into it, I haven't worked with dotnet core yet.

**Comment by SubZero0** [comment]
@velddev Solved with #6 since it's .NET Standard 1.1 now.

**Comment by velddev** [comment]
Yeah! i was about to mention this! Good job @SubZero0
