### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by Straafe** [velddev/Cleverbot.Net#9]
"Type or namespace "CleverbotSession" cannot be found "

Even after installing "Install-Package Cleverbot"

Just doesn't seem to work.

**Comment by velddev** [comment]
Let me check on this

**Comment by DynamicField** [comment]
Have you added an `using` statement to your code ?

**Comment by velddev** [comment]
No, he was right. The project weirdly enough didn't function the way it should've. should be fixed and posted on Nuget

**Comment by DynamicField** [comment]
Ah wait, did you use this on a .NET framework (classic, for example : 4.5) solution or a .NET standard one ?

**Comment by velddev** [comment]
No, I tested it with dotnet core 2.0, didn't unpack. which was weird, I'm guessing the version on Nuget was still the .Framework version. should be resolved now though
